<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CClappy" failures="2" tests="3" name="TestLogin" time="13.986" errors="0" timestamp="2025-06-02T14:54:03 IST">
  <testcase classname="test.LoginTest" name="testValidLogin" time="0.751">
    <failure type="java.lang.AssertionError" message="expected [Just a moment...] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [Just a moment...] but found [nopCommerce demo store. Login]
at test.LoginTest.testValidLogin(LoginTest.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase classname="test.LoginTest" name="testValidLogin" time="0.707">
    <failure type="java.lang.AssertionError" message="expected [Just a moment...] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [Just a moment...] but found [nopCommerce demo store. Login]
at test.LoginTest.testValidLogin(LoginTest.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase classname="test.LoginTest" name="testValidLogin" time="0.876"/>
</testsuite> <!-- TestLogin -->
